{"uuid":"64d192e0-dd4b-4fa8-98bf-0d377a36d06e","name":"Scenario Outline: The user is presented with error message for code with invalid syntax in tryEditor for Arrays in Python page","children":["7773e768-2522-4e1d-a98b-0403202e3589"],"befores":[{"name":"appHooks.Hooks.scenario(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673283501260,"stop":1673283501265}],"afters":[{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673283501280,"stop":1673283501280},{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673283502019,"stop":1673283502019},{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673283502371,"stop":1673283502371},{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"My screenshot","source":"6e18b0e1-96e9-4bf2-9c85-2b987a3bf3e8-attachment","type":"image/png"},{"name":"Myscreenshot","source":"28e52b07-ae0c-40a1-93a0-932970d5162f-attachment"}],"parameters":[],"start":1673283502407,"stop":1673283502818}],"start":1673283501260,"stop":1673283502818}