{"uuid":"96e4497c-66a6-45e0-b2ef-66f7e5e4c467","name":"Scenario Outline: The user is presented with error message for code with invalid syntax in tryEditor for Arrays in Python page","children":["33b2ef2e-f90d-4553-b34e-05a38d500e02"],"befores":[{"name":"appHooks.Hooks.scenario(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673380835831,"stop":1673380835831}],"afters":[{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673380835840,"stop":1673380835840},{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673380836188,"stop":1673380836188},{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673380836332,"stop":1673380836332},{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"My screenshot","source":"3e109f41-8243-46f3-a206-8e553f3d378e-attachment","type":"image/png"},{"name":"Myscreenshot","source":"457c8c0f-1578-4e29-a6d8-f548350c05d6-attachment"}],"parameters":[],"start":1673380836343,"stop":1673380836615}],"start":1673380835831,"stop":1673380836615}