{"uuid":"96e8af66-3a84-42fc-96c5-1d4e5ab9e0d7","name":"Scenario Outline: The user is presented with error message for invalid code in tryEditor for Max Consecutive Ones","children":["be60d3e7-bda9-4f07-a015-4b349f239927"],"befores":[{"name":"appHooks.Hooks.scenario(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673421185272,"stop":1673421185272}],"afters":[{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673421185399,"stop":1673421185400},{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673421185714,"stop":1673421185714},{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673421185877,"stop":1673421185877},{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"My screenshot","source":"4402504d-dabd-4797-b8d5-e55c7f9e8845-attachment","type":"image/png"},{"name":"Myscreenshot","source":"d7ad6701-a6b7-44c6-8b94-58c7f6fa21df-attachment"}],"parameters":[],"start":1673421185888,"stop":1673421186283}],"start":1673421185271,"stop":1673421186283}