{"uuid":"9c1b3a92-66da-4e20-9f73-dd9b8f75e7fe","name":"Scenario Outline: The user is presented with error message for code with invalid syntax in tryEditor for Arrays in Python page","children":["74bff055-671b-4431-8c10-c5b5ed833a48"],"befores":[{"name":"appHooks.Hooks.scenario(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673409753558,"stop":1673409753558}],"afters":[{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673409753558,"stop":1673409753558},{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673409753959,"stop":1673409753959},{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1673409754114,"stop":1673409754115},{"name":"appHooks.Hooks.afterstep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[{"name":"My screenshot","source":"b67d68b7-bd0d-4731-b890-09dc03ba63db-attachment","type":"image/png"},{"name":"Myscreenshot","source":"f117a63b-7270-4920-9a0d-2527d99db109-attachment"}],"parameters":[],"start":1673409754126,"stop":1673409754453}],"start":1673409753558,"stop":1673409754453}