<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-RSES787T" failures="5" tests="69" name="com.runner.Runner" time="210.369" errors="2" timestamp="2023-01-18T10:36:06 EST" skipped="0">
  <testcase classname="com.runner.Runner" name="runScenario" time="3.362"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="0.881"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="7.805"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.072">
    <failure message="Result do not match expected [submission success] but found [ Some Tests failed. Please review code]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Result do not match expected [submission success] but found [ Some Tests failed. Please review code]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at com.stepDefinations.ArraysStepDef.the_user_should_be_presented_with_successful_submission_message(ArraysStepDef.java:133)
at ✽.The user should be presented with successful submission message(file:///C:/Users/valli/Git/DS-ALGO/src/test/resources/features/5arrays.feature:130)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="0.758"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.150"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.463"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.320"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="5.350"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.392"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="1.941"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.412"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.526"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.714">
    <failure message="expected [password should contain atleast eight characters.] but found [password_mismatch:The two password fields didn’t match.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [password should contain atleast eight characters.] but found [password_mismatch:The two password fields didn’t match.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.stepDefinations.RegisterStepDef.user_should_get_password_atleast_eight_char_error_message(RegisterStepDef.java:145)
at ✽.user should get password atleast eight char error message "password should contain atleast eight characters."(file:///C:/Users/valli/Git/DS-ALGO/src/test/resources/features/2register.feature:81)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.583"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.270"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="0.687"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.426"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.683"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.003"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.015"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.898"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.601">
    <error message="stale element reference: element is not attached to the page document
  (Session info: chrome=109.0.5414.75)
For documentation on this error, please visit: https://selenium.dev/exceptions/#stale_element_reference
Build info: version: &#039;4.7.1&#039;, revision: &#039;c6795baf1a3&#039;
System info: os.name: &#039;Windows 11&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;17.0.5&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [271b72d85708c9435cd51b6c95f0dd61, getElementText {id=fb993dc3-7ae7-478f-8f54-1ccecaf0b40a}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 109.0.5414.75, chrome: {chromedriverVersion: 109.0.5414.74 (e7c5703604da..., userDataDir: C:\Users\valli\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:52413}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:52413/devtoo..., se:cdpVersion: 109.0.5414.75, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on WINDOWS (271b72d85708c9435cd51b6c95f0dd61)] -&gt; id: id_username]
Session ID: 271b72d85708c9435cd51b6c95f0dd61" type="org.openqa.selenium.StaleElementReferenceException">
      <![CDATA[org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=109.0.5414.75)
For documentation on this error, please visit: https://selenium.dev/exceptions/#stale_element_reference
Build info: version: '4.7.1', revision: 'c6795baf1a3'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [271b72d85708c9435cd51b6c95f0dd61, getElementText {id=fb993dc3-7ae7-478f-8f54-1ccecaf0b40a}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 109.0.5414.75, chrome: {chromedriverVersion: 109.0.5414.74 (e7c5703604da..., userDataDir: C:\Users\valli\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:52413}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:52413/devtoo..., se:cdpVersion: 109.0.5414.75, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on WINDOWS (271b72d85708c9435cd51b6c95f0dd61)] -> id: id_username]
Session ID: 271b72d85708c9435cd51b6c95f0dd61
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:551)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:257)
at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:207)
at jdk.internal.reflect.GeneratedMethodAccessor116.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:52)
at jdk.proxy2/jdk.proxy2.$Proxy44.getText(Unknown Source)
at com.pageObjects.RegisterPage.validatecompare(RegisterPage.java:155)
at com.stepDefinations.RegisterStepDef.user_should_get_password_not_similar_to_username_error_message(RegisterStepDef.java:171)
at ✽.user should get password not similar to username error message "password can not be similar as username"(file:///C:/Users/valli/Git/DS-ALGO/src/test/resources/features/2register.feature:98)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="13.947"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="0.387"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="0.639"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.412"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.279"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.322"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="0.522"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.325">
    <error message="element not interactable
  (Session info: chrome=109.0.5414.75)
Build info: version: &#039;4.7.1&#039;, revision: &#039;c6795baf1a3&#039;
System info: os.name: &#039;Windows 11&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;17.0.5&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [271b72d85708c9435cd51b6c95f0dd61, sendKeysToElement {id=09daeb62-c086-4211-b424-125103c2cc12, value=[Ljava.lang.CharSequence;@7b6824db}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 109.0.5414.75, chrome: {chromedriverVersion: 109.0.5414.74 (e7c5703604da..., userDataDir: C:\Users\valli\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:52413}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:52413/devtoo..., se:cdpVersion: 109.0.5414.75, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on WINDOWS (271b72d85708c9435cd51b6c95f0dd61)] -&gt; xpath: //textarea[@tabindex=&#039;0&#039;]]
Session ID: 271b72d85708c9435cd51b6c95f0dd61" type="org.openqa.selenium.ElementNotInteractableException">
      <![CDATA[org.openqa.selenium.ElementNotInteractableException: element not interactable
  (Session info: chrome=109.0.5414.75)
Build info: version: '4.7.1', revision: 'c6795baf1a3'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [271b72d85708c9435cd51b6c95f0dd61, sendKeysToElement {id=09daeb62-c086-4211-b424-125103c2cc12, value=[Ljava.lang.CharSequence;@7b6824db}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 109.0.5414.75, chrome: {chromedriverVersion: 109.0.5414.74 (e7c5703604da..., userDataDir: C:\Users\valli\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:52413}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:52413/devtoo..., se:cdpVersion: 109.0.5414.75, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on WINDOWS (271b72d85708c9435cd51b6c95f0dd61)] -> xpath: //textarea[@tabindex='0']]
Session ID: 271b72d85708c9435cd51b6c95f0dd61
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:551)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:257)
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:113)
at jdk.internal.reflect.GeneratedMethodAccessor164.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:52)
at jdk.proxy2/jdk.proxy2.$Proxy44.sendKeys(Unknown Source)
at com.utils.Utils.enterCodePractice(Utils.java:131)
at com.pageObjects.ArraysPage.enterCodePractice(ArraysPage.java:141)
at com.stepDefinations.ArraysStepDef.the_user_enter_valid_python_code_in_try_editor_from_sheet_and_for_the_question(ArraysStepDef.java:185)
at ✽.The user enter valid python code in tryEditor from sheet "pythonCode" and 3 for the question(file:///C:/Users/valli/Git/DS-ALGO/src/test/resources/features/5arrays.feature:108)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.875"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.390"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.381"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="5.067"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.528"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.745">
    <failure message="Result do not match expected [submission success] but found [ No tests were collected]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Result do not match expected [submission success] but found [ No tests were collected]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at com.stepDefinations.ArraysStepDef.the_user_should_be_presented_with_successful_submission_message(ArraysStepDef.java:133)
at ✽.The user should be presented with successful submission message(file:///C:/Users/valli/Git/DS-ALGO/src/test/resources/features/5arrays.feature:170)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.407"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="0.819"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.577"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.408"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="1.364"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.316"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="1.952"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.401"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="4.746"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.006"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="1.023"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.619">
    <failure message="expected [please enter valid password format] but found [password_mismatch:The two password fields didn’t match.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [please enter valid password format] but found [password_mismatch:The two password fields didn’t match.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.stepDefinations.RegisterStepDef.user_should_get_enter_valid_input_error_message(RegisterStepDef.java:159)
at ✽.user should get enter valid input error message "please enter valid password format"(file:///C:/Users/valli/Git/DS-ALGO/src/test/resources/features/2register.feature:89)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.046"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="1.972"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.526"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="0.842"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.761"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.768"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.111"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.631"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.203"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.387"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.839"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.291"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.405"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.358"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.704">
    <failure message="Result do not match expected [submission success] but found [Error occurred during submission]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Result do not match expected [submission success] but found [Error occurred during submission]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at com.stepDefinations.ArraysStepDef.the_user_should_be_presented_with_successful_submission_message(ArraysStepDef.java:133)
at ✽.The user should be presented with successful submission message(file:///C:/Users/valli/Git/DS-ALGO/src/test/resources/features/5arrays.feature:150)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.508"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.835"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="2.600"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.404"/>
  <system-out/>
  <testcase classname="com.runner.Runner" name="runScenario" time="3.409"/>
  <system-out/>
</testsuite> <!-- com.runner.Runner -->
